### PR TITLE
Merge branch 'development' into main

### PR DESCRIPTION
**Pull request by PuneetGopinath**
## Checks

I have...

- [x] Read and understood the [Contributing Guidelines][contributing]
- [x] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [x] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

Time to test, merge, and release new version!

Closes #

[contributing]: https://github.com/Welcome-Bot/welcome-bot/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
Never squash and merge this pr!!

**Comment by PuneetGopinath** [comment]
Waiting for https://github.com/discordjs/discord.js/pull/6114 to be merged

**Comment by PuneetGopinath** [comment]
Need to fix errors in refactor/cmds branch.

**Review by abhijoshi2k — APPROVED** [review]

**Comment by PuneetGopinath** [comment]
@abhijoshi2k I will test.

**Pull request merged**
