### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by PuneetGopinath**

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
Cool!
I just signed up for crowdin, but this is a trial, so in 7 days my trial will expire.
We need to finish en-US language ASAP, @abhijoshi2k

**Comment by PuneetGopinath** [comment]
@abhijoshi2k I think after this translation, and a lot of other stuff, can we go for a new major release v2?

**Comment by abhijoshi2k** [comment]
> Cool!
> I just signed up for crowdin, but this is a trial, so in 7 days my trial will expire.
> We need to finish en-US language ASAP, @abhijoshi2k
> You will see all those commits are unverified as they are automated by crowdin

Why are we dependent on trial version which will expire in 7 days? What after that?

**Comment by PuneetGopinath** [comment]
> > Cool!
> > I just signed up for crowdin, but this is a trial, so in 7 days my trial will expire.
> > We need to finish en-US language ASAP, @abhijoshi2k
> > You will see all those commits are unverified as they are automated by crowdin
> 
> Why are we dependent on trial version which will expire in 7 days? What after that?

Just I want some help from there, I think I need money to subscribe. I add dependent as it will at least copy all en-US files, and create new directories with most used languages. If this is automated, I don't need to search for most used languages, and manually create new directories, and copy them.

**Comment by PuneetGopinath** [comment]
Hmm, because you said auto this, I checked pricing, I didn't know it is free of cost. I will subscribe!!

**Comment by abhijoshi2k** [comment]
I think their translation will he API based. So simply copying won't work.

**Comment by PuneetGopinath** [comment]
> I think their translation will he API based. So simply copying won't work.

Not API, we need directories, I have created locales folder, see dev branch

**Comment by abhijoshi2k** [comment]
@PuneetGopinath Have you tested it?

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath Have you tested it?

Of course

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath Have you tested it?

But, yet
I didn't make commands to change language and store to db

**Comment by abhijoshi2k** [comment]
> > @PuneetGopinath Have you tested it?
> 
> But, yet
> I didn't make commands to change language and store to db

Do you want me to add the property?

**Comment by PuneetGopinath** [comment]
> > > @PuneetGopinath Have you tested it?
> > 
> > 
> > But, yet
> > I didn't make commands to change language and store to db
> 
> Do you want me to add the property?

I can do that from website, I already those things
I need to create a command, but I have work

**Pull request merged**
