### PR TITLE
feat: add dashboard & eslint linter

### LINKED ISSUE #154: Feature request: Add dashboard!!
Please check these things before submitting your issue:

- [x] I searched for duplicate or closed feature request [here](https://github.com/Welcome-Bot/welcome-bot/issues?q=is%3Aissue)

**Is your feature request related to a problem? Please describe.**

N/A.

**Describe the solution you'd like**

I love dashboards, we can easily do this using express. I will help too. Can't assure that we will host it, until we get a domain.

**Describe alternatives you've considered**

N/A.

**Additional context**

N/A.

### PR DESCRIPTION
**Pull request by PuneetGopinath**
## Checks

I have...

- [x] Read and understood the [Contributing Guidelines][contributing]
- [x] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [x] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

Add dashboard

Closes #154

[contributing]: https://github.com/Welcome-Bot/welcome-bot/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Dashboard ready, csrf implementation left.

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Please review!!
Test dashboard once before review
https://welcome-bot-production.up.railway.app/dashboard

**Comment by abhijoshi2k** [comment]
https://welcome-bot-production.up.railway.app/
This route just outputs ok after login

**Comment by PuneetGopinath** [comment]
> https://welcome-bot-production.up.railway.app/
> This route just outputs ok after login

Yes, then what to output, or should I redirect?

**Comment by abhijoshi2k** [comment]
> > https://welcome-bot-production.up.railway.app/
> > This route just outputs ok after login
> 
> Yes, then what to output, or should I redirect?

Yes. You should

**Comment by PuneetGopinath** [comment]
@abhijoshi2k Now I should once test vote webhooks

**Comment by PuneetGopinath** [comment]
It's good, @abhijoshi2k Please review

**Review by abhijoshi2k — APPROVED** [review]

**Comment by abhijoshi2k** [comment]
Is this ready now?

**Comment by PuneetGopinath** [comment]
> Is this ready now?

Yea

**Pull request merged**
