### PR TITLE
v1.5

### PR DESCRIPTION
**Pull request by PuneetGopinath**
## Checks

I have...

- [x] Read and understood the [Contributing Guidelines][contributing]
- [x] Updated any nessecary files such as the README.md and/or CHANGELOG.md.

## Type of Pull request

- [x] **Minor Change**  
  This Pull request doesn't break existing configuration.
- [ ] **Major Change**  
  This Pull request will break existing configuration.
- [ ] **Bug fix**  
  This Pull request will fix a (critical) bug.
- [ ] **Documentation**  
  This Pull request only changes documentation (README.md, CHANGELOG.md, etc.)
- [ ] **Other:** `__________` 

## Description

Release v1.5.0

Closes #

[contributing]: https://github.com/Welcome-Bot/welcome-bot/blob/main/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by abhijoshi2k** [comment]
Please make it ready for review @PuneetGopinath

**Comment by PuneetGopinath** [comment]
It is not ready, sorry

**Comment by PuneetGopinath** [comment]
Sorry, I wanted to say that the emoji problem it there, I will remove it currently

**Comment by PuneetGopinath** [comment]
You can review now, @abhijoshi2k

**Comment by PuneetGopinath** [comment]
> You can review now, @abhijoshi2k

Please react if read my comment

**Review by abhijoshi2k — APPROVED** [review]

**Pull request merged**
